import type { Metadata } from "next";
import "./globals.css";
import { PuterAuth } from "@/components/ui";
import ContextProvider from "@/context-api/_provider";
import { MessageQueue } from "@/components/ui/message-queue";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ContextProvider>
          <PuterAuth />
          <MessageQueue />
          <>{children}</>
        </ContextProvider>
      </body>
    </html>
  );
}
